name: 'CI: Lint'

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run lint (Prettier & ESLint)
              run: npm run lint

            - name: Run Svelte check
              run: npm run check
